import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Basket, LineItem, processCart } from '@/scripts/cart.js'
import Sidebar from '@/components/sidebar';
import Logo from '@/components/logo';
import Filter from '@/components/filter';
import Item from '@/components/item';

export default function Home() {
  const [basket, setBasket] = useState<Basket>(new Basket([], []));

  useEffect(() => {
    // retrieve id from url
    var id = new URL(window.location.toLocaleString()).searchParams.get("id");

    // query database
    fetch("https://superbasket-55e27-default-rtdb.asia-southeast1.firebasedatabase.app/" + id + ".json")
    .then((response) => {
      return response.json();
    })
    .then((body) => {
      var cartReceived = body[Object.keys(body)[0]]
      console.log(cartReceived);
      
      // process raw woolworths cart data
      var basket : Basket = processCart(cartReceived);
      console.log(basket);
      setBasket(basket);

    })
    .catch((error) => {
      console.error(error);
    })
  }, [])

  return (
    <>
      <Head>
        <title>Superbasket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <header className="header">
          <Logo/>
        </header>

        <Sidebar>
          <Logo/>
          <div className='column-list filters'>
            <h2>Filter Items</h2>
            <Filter display="Fruit & Veg" filter=""/>
            <Filter display="Meat, Seafood, & Deli" filter=""/>
            <Filter display="Bakery" filter=""/>
            <Filter display="Dairy, Eggs, & Fridge" filter=""/>
            <Filter display="Health & Wellness" filter=""/>
            <Filter display="Lunch Box" filter=""/>
            <Filter display="Pantry" filter=""/>
            <Filter display="Snacks & Confectionary" filter=""/>
            <Filter display="Freezer" filter=""/>
            <Filter display="Drinks" filter=""/>
          </div>
        </Sidebar>
      
        <div id="body" className="body">
          
          <div className="column-list--large">
            <div className="panel items column-list">
              <h2>Food Items</h2>

              {basket.foodItems.map((item: LineItem, index: number) => (
                <Item key={index} item={item}/>
              ))}

            </div>

            <div className="panel items column-list">
              <h2>Non-Food Items</h2>

              {basket.nonFoodItems.map((item: LineItem, index: number) => (
                <Item key={index} item={item}/>
              ))}

            </div>
          </div>
          <div className="panel insights"></div>
          {/*JSON.stringify(basket)*/}
        </div>
        
      </main>
    </>
  )
}
